### ISSUE TITLE
rewrite only for SPF enabled domains

### ISSUE THREAD

**Issue by MuhKuh7** [roehling/postsrsd#17]
Hi, this is more a question than an issue, but github seems to have no other way to ask questions.

Is it possible to enable the SRS rewrite only for domains that have a SPF record? For example I would like to have a rewrite when a gmail.com mail is forwarded, but not when a non SPF domain example.com mail is forwarded.

**Comment by uschindler** [comment]
I think that should be relatively easy to implement:

You get the envelope e-mail address of sender by postfix (because it is the one you want to rewrite). Just extract domain name from it (you do that anyways to check the list of excluded domains). Do a DNS lookup of the TXT record of the domain extracted. If the TXT as returned by libc/DNS server contains the string "spf", the envelope sender's address is SPF enabled. In that case you need to do SRS. Otherwise it is useless.

This is an additional DNS lookup on every request, but if the mailserver has done the "policy-spf" checks already, the TXT record is in the DNS cache already...
