### ISSUE TITLE
Rewrite only specific addresses

### ISSUE THREAD

**Issue by szepeviktor** [roehling/postsrsd#43]
Good morning!

My mail server has local accounts and it also forwards messages.

How is it possible to rewrite only those addresses that are in forwarded messages?

**Comment by roehling** [comment]
As mentioned in the "Known Issues" section of the README, that's not possible due to the way PostSRSd is interacting with Postfix.

**Comment by szepeviktor** [comment]
Thanks.

**Comment by aptalca** [comment]
I just noticed something, perhaps it could help others.

The way I set up my server is that I'm using mail.domain1.com as myhostname and domain1.com as myorigin

I have a couple of virtual mailboxes set up as well as virtual aliases

Dovecot defines the users `user1@domain1.com` and `user2@domain2.com` with their credentials.

In my virtual alias map file, I list the following:
`user1@domain1.com user1 user234@gmail.com`
With this setup, all e-mails coming to user1@domain1.com get delivered to user1@domain.com's mailbox as well as forwarded to the gmail address. In this scenario, the local delivery does not have SRS appended, but the gmail forward does. Great.

But for an e-mail address with a different virtual mailbox, I have the following:
`user2@domain2.com user2@domain2.com user234@gmail.com`
In this scenario, both the local delivery and the gmail forward has SRS appended.

Notice that for the myhostname based e-mail accounts, I enter them as just the username `user1` in the virtual alias map and they are ignored by postsrsd (cleanup daemon). I can't do that for other domains, they have to be entered in as the full e-mail address. The reason I discovered this is because when I entered the full e-mail address for the myhostname based accounts, e-mails were not delivered to the local accounts and I had errors in the logs.

Maybe I set up my postfix server incorrectly and this is an unintended side effect, but the server is working beautifully with multiple domains and at least for the main domain, the local delivery envelope is unmodified. I may be mixing up virtual accounts with local ones but the postfix logs aren't complaining (at first I had the domain1.com listed in mydestination and postfix was not happy about it).

Anyway, I'm just learning about postfix and dovecot and thanks to you postsrsd is working beautifully and all my mails are delivered without issues.
