### ISSUE TITLE
RPM Spec file for postsrsd

### ISSUE THREAD

**Issue by timeos** [roehling/postsrsd#5]
Hello,
I meantime I have created spec file for building RPM package of your project. It is more better to have every software installed as package and not just building/deploying as is. 
This spec file can work also for any rpm-like (compatible) distribution and it is available here: http://pastebin.com/eK7Btr0e

Here are some info how it works:
- you have not defined any version numbering for postsrsd, so I decided to use version 0.1 in this particular spec file. maybe it will be good idea to have some initial version number for your project. 
- this spec file is not performing "make install" provided by your package because:
  1) a bit different file locations are used for postsrsd binary and for documents (/usr prefix instead of /usr/local)
  2) there is still problem with postinstall cmake script - centos's cmake 2.6.4 does not implement "FILE_PERMISSIONS OWNER_READ OWNER_WRITE" in "file()" function and the line 46 is always failing (I have not checked it well before)
- postsrsd.secret is created as postinstall script to ensure uniqueness of included secret (it is generated same way as you do it in your cmake postinstall script. File permissions are corrected as well.
- chroot directory is choosed as /var/lib/postsrsd (standard location for RH systems) with corresponding permissions which are defined as well within spec file. 

The opened questions:
- I defined build requirements and dependency as follows:
  BuildRequires:  cmake make gcc
  Requires:       postfix
  but I am not sure if I miss something or they are fine.
- During package uninstalling the postsrsd secret file is deleted. But not sure if it will be better just to rename it (with standard .rpmsave extension).
- URL package availability: I heard that there is chance to get corresponding package version directly using correct github URL path - like this one: "http://github.com/masterzen/mysql-snmp/tarball/v1.0rc2". Something similar will be fine for your project once you decided to give it some version numbering - hopefully gihub will do the rest (URL version availability for direct download). 

If you think this spec file is useful, you can put it in some "contrib" folder in your project. Just wanted to make this project more available for deployment as possible.

**Comment by Natolumin** [comment]
I have also made a specfile for EL7 and fedora (basically redhat systems with systemd): https://gist.github.com/Natolumin/9f18aee5c911f763b9ac

The patch file that comes with it is commit 855bd46 (with a workaround for #44) which was not included in the 1.3 release. It should be dropped, as well as lines 9 and 22 of the [specfile](https://gist.github.com/Natolumin/9f18aee5c911f763b9ac#file-postsrsd-spec-L9) when building from master or the next tagged release

I unfortunately do not have a redhat system without systemd to make a specfile for previous systems, but since this issue is now two years old, maybe it is not so necessary ?

**Comment by roehling** [comment]
Closing this issue, since it seems to be stale. Feel free to reopen.
