### ISSUE TITLE
Only rewrite sender when forwarding and dynamically exclude local domains

### ISSUE THREAD

**Issue by chaosmaster** [roehling/postsrsd#76]
A setup like this only rewrites the sender for mails going to external adresses
Additionally local domains are excluded from SRS

main.cf:
```
default_transport = smtp:127.0.0.1:10027
recipient_canonical_maps=tcp:localhost:10002
recipient_canonical_classes=envelope_recipient,header_recipient
```
master.cf:
```
cleanup-srs   unix  n       -       -       -       0       cleanup
        -o sender_canonical_maps=mysql:/etc/postfix/mysql_virtual_local_email.cf,tcp:localhost:10001
        -o sender_canonical_classes=envelope_sender

127.0.0.1:10027 inet    n       -       -       -       -       smtpd
        -o cleanup_service_name=cleanup-srs
        -o smtpd_tls_security_level=none
        -o content_filter=smtp:
        -o smtpd_recipient_restrictions=permit_mynetworks,reject
```

```
user = <DBUSER>
password = <DBPASS>
dbname = <DATABASE>
query = SELECT '%s' FROM domains WHERE domain='%d'
hosts = 127.0.0.1
```

The query just returns the address if the domain is valid, and therefore doesn't map to an SRS-address

**Comment by trefzer** [comment]
Thanks for you're idea, I just use it a little bit different:
I use a transport map, that chooses your srs as transport if destination email starts with 'srs=' (so the redirection goes to srs=emailuser@emaildomain.org. In cleanup-srs I rewrite the destination address to emailuser@emaildomain.org, (so it's sort of opt-in for srs).

main.cf:
`transport_maps = regexp:/regex_transport_srs`

regex_transport_srs:
`/^srs=.*@.*$/      smtp:127.0.0.1:10027`

master.cf:
```
cleanup-srs unix  n       -       -       -       0       cleanup
      -o sender_canonical_maps=mysql:/mysql_virtual_domains_no_srs_maps.cf,tcp:127.0.0.1:10001
      -o sender_canonical_classes=envelope_sender
      -o recipient_canonical_maps=regexp:/regex_sender_canonical_srs

127.0.0.1:10027 .... (like above)
```

/regex_sender_canonical_srs:
`/^srs=(.*)@(.*)$/      ${1}@${2}`

_Remark: you could also make an opt-out solution like this, if you use the default transport ...._

**Comment by roehling** [comment]
Hey, I really like your solutions! As soon as I find time, I will put them into the README.

**Comment by fisher006** [comment]
@trefzer I'm trying use your configuration in clean installation of https://www.iredmail.org
But doesn't work.

When I'm send message from yahoo -> local-alias -> gmail I don't have SRS headers at all.


Here is my configuration



in /etc/postfix/

two files:

```
-rw-r--r--   1 root root       28 04-10 09:18 regex_sender_canonical_srs
-rw-r--r--   1 root root       35 04-10 09:18 regex_transport_srs
```

in 

/etc/postfix/mysql


`mysql_virtual_domains_no_srs_maps.cf` with SQL query


and in main.cnf


transport_maps = regexp:/etc/postfix/regex_transport_srs
recipient_canonical_maps=tcp:localhost:10002
recipient_canonical_classes=envelope_recipient,header_recipient


and master

cleanup-srs unix  n	  -	  -	  -	  0	  cleanup
      -o sender_canonical_maps=mysql:/etc/postfix/mysql/mysql_virtual_domains_no_srs_maps.cf,tcp:127.0.0.1:10001
      -o sender_canonical_classes=envelope_sender
      -o recipient_canonical_maps=regexp:/etc/postfix/regex_sender_canonical_srs

127.0.0.1:10027 inet    n	-	-	-	-	smtpd
        -o cleanup_service_name=cleanup-srs
        -o smtpd_tls_security_level=none
        -o content_filter=smtp:
        -o smtpd_recipient_restrictions=permit_mynetworks,reject

**Comment by trefzer** [comment]
where does the local alias points to ? (it needs to point to srs=gmailaddress, otherwise the postsrs transport is not used.
I can also state, that my setup works in my prod and test setup. So probably you need to debug a bit (is the transport used at all ? what does the log say ? what does postsrs log say ? etc.)

**Comment by RF3** [comment]
For those who don't want to use a SQL server just for the list of local mail addresses that SRS shouldn't be used on, there's a simpler and faster way. Replace

`mysql:/etc/postfix/mysql_virtual_local_email.cf`

with

`hash:/etc/postfix/no_srs`

Now add every existing local mail address to /etc/postfix/no_srs. Each entry looks like this:

```
name1@domain1     name1@domain1
name2@domain1     name2@domain1
...
name1@domain2     name1@domain2
name2@domain2     name2@domain2
```

If you already have a virtual_alias_maps file, then the no_srs table is not much different. Instead of returning the name of a local mailbox or an external mail address, no_srs returns the same address instead. A lookup hit therefore means to skip SRS (these table lookups basically simulate an already rewritten address, but in fact the address stays the same). A miss means that postsrsd is called next via

`tcp:localhost:10001`

and the mail address is rewritten. Don't forget to create/update the lookup table (no_srs.db) after each change to no_srs with

`postmap hash:/etc/postfix/no_srs`

**Comment by RhysMcW** [comment]
I installed postsrsd a few days ago and noticed all mail got SRS tagged and not just forwarded mail.
I then came across this topic and really like what @chaosmaster posted.
I tried the setup but keep getting and error on any outbound email (forwarded or not)

```
Oct  4 19:04:12 McWilliamsNX opendkim[19320]: 3B343100E5731: DKIM-Signature field added (s=mail, d=local.domain)
Oct  4 19:04:12 McWilliamsNX postfix/qmgr[32157]: 3B343100E5731: from=<email@local.domain>, size=1311, nrcpt=1 (queue active)
Oct  4 19:04:12 McWilliamsNX postfix/smtpd[32251]: connect from unknown[127.0.0.1]
Oct  4 19:04:12 McWilliamsNX postfix/smtpd[32251]: fatal: host/service localhost/8891 not found: Device or resource busy
Oct  4 19:04:12 McWilliamsNX postfix/smtpd[32226]: disconnect from localhost[127.0.0.1]
Oct  4 19:04:12 McWilliamsNX opendkim[19320]: cache: 244 queries, 68 hits (27%), 73 expired, 84 keys
Oct  4 19:04:13 McWilliamsNX postfix/master[32155]: warning: process /usr/libexec/postfix/smtpd pid 32251 exit status 1
Oct  4 19:04:13 McWilliamsNX postfix/master[32155]: warning: /usr/libexec/postfix/smtpd: bad command startup -- throttling
Oct  4 19:04:13 McWilliamsNX postfix/smtp[32250]: 3B343100E5731: to=<email@external.domain>, relay=127.0.0.1[127.0.0.1]:10027, delay=1.4, delays=0.4/0.02/1/0, dsn=4.4.2, status=deferred (lost connection with 127.0.0.1[127.0.0.1] while receiving the initial server greeting)
```

The port 8891 is my DKIM setup but if I remove the DKIM relevant settings in main.cf I still get the same error but for port 10002
`fatal: host/service localhost/10002 not found: Device or resource busy`

**Comment by RhysMcW** [comment]
update on my previous post...
been playing around a little, I changed the "localhost" in the config to be 127.0.0.1 and now the outbound mail no longer fails as previous BUT it doesn't use my relayhost setting at all and tries to send direct to the target SMTP server but being on a dynamic IP it gets denied by that target server...
now to try figure out how to get the process to use the relayhost (and  I wonder what else it's no longer doing???)???

**Comment by chaosmaster** [comment]
I believe you may have to change your http://www.postfix.org/postconf.5.html#relay_transport instead of default_transport

**Comment by RhysMcW** [comment]
Thanks for the reply @chaosmaster , it looked promising...
I changed the default_transport to be relay_transport in main.cf and this solved the standard outbound email working again by using the relayhost.
Now it seems to skip the SRS rewrite. I tested by sending from my gmail account to a local address that forwards to an external address. The email came in and attempted to send to the forward address (via the relayhost) but without doing the SRS rewrite...

**Comment by chaosmaster** [comment]
@RhysMcW 
main.cf:
[code]
relay_transport = smtp:127.0.0.1:10027
[/code]
master.cf:
[code]
        -o content_filter=relay
[/code]

**Comment by RhysMcW** [comment]
Thanks, gave that a try, unfortunately no difference, still no SRS rewriting.

**Comment by gklanderman** [comment]
RhysMcW did you ever figure out your problem?

I found this issue with great interest as it seemed like I should be able to use a similar technique to apply a content filter only to emails that come in on port 25 (but not 587) and which are being forwarded externally.  I attempted to use '-o default_transport=smtp:127.0.0.1:10027' on the port 25 smtpd in master.cf, and then made a similar entry for the 127.0.0.1:10027 smtpd in master.cf as chaosmaster, but instead of setting cleanup_service_name, instead set content_filter to point to my content filter.  But it is not working at all, no mail appears to be getting routed through 127.0.0.1:10027 or to my content filter.

Previously I had added '-o content_filter=...' in the port 25 smtpd, and that worked but was applied to both locally delivered and forwarded mail.

I currently suspect the issue with setting '-o default_transport=smtp:127.0.0.1:10027' in the port 25 smtpd is that the setting is used by a later process down the chain, and probably after mail from port 587 has merged into the processing chain.  I'm going to play with some ideas around confirming that next, but thought I would post here first since it seems a few of you understand how postfix works much more deeply than I do, and have already been playing with ideas along these lines.

**Comment by MeneerDoktoor** [comment]
Having the same issue here. Trying to relay it to a different server, which is a spam filter, but no luck so far.

**Comment by gklanderman** [comment]
I decided I will need to create a multi-instance postfix configuration to do what I want but I think it will work.  Unfortunately I have not had time to actually try it yet...

**Comment by kevinvalk** [comment]
I think I am missing something, but why can we not just use the canonical_maps without the extra internal SMTPD hop? Is there a reason for having the extra SMTPD service?
```
sender_canonical_maps = mysql:/etc/postfix/mysql_virtual_local_email.cf:127.0.0.1:10001
sender_canonical_classes = envelope_sender
recipient_canonical_maps = tcp:127.0.0.1:10002
recipient_canonical_classes = envelope_recipient, header_recipient
```
This is my config (well I am using a hash:mailboxes instead of mysql), but I believe this is working just fine. I.e. I read this as, rewrite the sender address to the sender address if the mailbox exist, if not, we are using postsrsd.

Anyone that can shine some light on why originally an extra SMTPD hop was introduced @chaosmaster?

**Comment by chaosmaster** [comment]
Wouldn't that also rewrite the senders of all incoming mails?

**Comment by kevinvalk** [comment]
> Wouldn't that also rewrite the senders of all incoming mails?

You are correct...

Refusing to give up, I started playing around with `receive_override_options` and `smtp_generic_maps`. Alas, I was unable to get that to work for only the case when we are forwarding (and only changing the envelop).

I mean, your solution still works great :) and it works perfectly. Just for future reference, I have:

**main.cf**
```
## Sender Rewrite Scheme (SRS)
default_transport = smtp:127.0.0.1:10027
recipient_canonical_maps = tcp:127.0.0.1:10002
recipient_canonical_classes = envelope_recipient, header_recipient

```

**master.cf**
```
cleanup-srs     unix n - - - 0 cleanup
  -o syslog_name=postfix/srs
  -o sender_canonical_maps=hash:/etc/postfix/database/mailboxes,tcp:127.0.0.1:10001
  -o sender_canonical_classes=envelope_sender

127.0.0.1:10027 inet n - - - - smtpd
  -o syslog_name=postfix/srs
  -o smtpd_milters=
  -o cleanup_service_name=cleanup-srs
  -o smtpd_tls_security_level=none
  -o content_filter=smtp:
  -o smtpd_recipient_restrictions=permit_mynetworks,reject
```
_Note: smtpd_milters I put to empty to prevent rspamd from scanning twice_

**Comment by RedJohn14** [comment]
Hello everyone,

If I past this on my **master.cf** my postfix won't restart "postfix/master[27350]: terminating on signal 15".

If I removed the mysql query "**mysql:/etc/postfix/mysql_virtual_local_email.cf**" from the master.cf the postfix service is up.

`cleanup-srs   unix  n       -       -       -       0       cleanup
        -o sender_canonical_maps=mysql:/etc/postfix/mysql_virtual_local_email.cf,tcp:localhost:10001
        -o sender_canonical_classes=envelope_sender

127.0.0.1:10027 inet    n       -       -       -       -       smtpd
        -o cleanup_service_name=cleanup-srs
        -o smtpd_tls_security_level=none
        -o content_filter=smtp:
        -o smtpd_recipient_restrictions=permit_mynetworks,reject`


Any ideas what I can do? I also used postfix with amavis for spam protection. In my **main.cf** I have this:
`content_filter=smtp-amavis:[127.0.0.1]:10024

recipient_canonical_maps=tcp:localhost:10002
recipient_canonical_classes= envelope_recipient
`

I have no default transport any ideas?
